# Generated by Django 6.0.6 on 2026-06-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoFpy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('imagem1', models.CharField(max_length=100)),
                ('imagem2', models.CharField(max_length=100)),
                ('imagem3', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
