# Generated by Django 6.0.6 on 2026-06-22 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoFpy', '0002_espaco'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='espaco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjetoFpy.espaco'),
        ),
        migrations.AddField(
            model_name='aluguel',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProjetoFpy.usuario'),
        ),
    ]
