# Generated by Django 5.2 on 2026-06-24 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoFpy', '0003_aluguel_espaco_aluguel_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espaco',
            name='imagem1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='espaco',
            name='imagem2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='espaco',
            name='imagem3',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='EspacoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.FileField(upload_to='espacos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('espaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='ProjetoFpy.espaco')),
            ],
            options={
                'ordering': ['criado_em', 'id'],
            },
        ),
    ]
