# Generated by Codex on 2026-06-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoFpy', '0004_alter_espaco_imagem1_alter_espaco_imagem2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
