# Generated by Django 6.0.6 on 2026-07-02 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoFpy', '0006_rename_cpf_to_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluguel',
            name='duracao',
        ),
    ]
