# Generated by Django 6.0.6 on 2026-07-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetoFpy', '0007_remove_aluguel_duracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacoimagem',
            name='imagem',
            field=models.CharField(max_length=1255),
        ),
    ]
